<?php

namespace unit;

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;
use CodeIgniter\Test\FeatureTestTrait;

use Tests\Support\Database\Seeds\UserSeeder;

class LoginTest extends CIUnitTestCase
{
	use DatabaseTestTrait;

	use FeatureTestTrait;

	// For Migrations
	protected $migrate     = true;
	protected $migrateOnce = false;
	protected $refresh     = true;
	protected $namespace   = 'App';

	// For Seeds
	protected $seedOnce = false;
	protected $seed     = UserSeeder::class;

	protected $users;

	protected function setUp(): void
	{
		parent::setUp();

		$this->users = new \App\Models\UserModel();
	}

	protected function tearDown(): void
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}


	public function testCanViewLogin()
	{
		$response = $this->get('/');
		$response->assertStatus(200);
		$response->assertSee('Login');
	}

	public function testCanLogin()
	{
		$response = $this->call('post', 'login/create',
			['email' => 'steviebuzz+user@gmail.com', 'password' => 'testme']);

		//$response->assertRedirect();
		$response->assertSessionHas('user_id');
	}
}