<?php

namespace App\Database;

use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;

use Tests\Support\Database\Seeds\UserSeeder;

class UserModelTest extends CIUnitTestCase
{
	use DatabaseTestTrait;

	// For Migrations
	protected $migrate     = true;
	protected $migrateOnce = false;
	protected $refresh     = true;
	protected $namespace   = 'App';

	// For Seeds
	protected $seedOnce = false;
	protected $seed     = UserSeeder::class;

	protected $users;

	protected function setUp(): void
	{
		parent::setUp();

		$this->users = new \App\Models\UserModel();
	}

	protected function tearDown(): void
	{
		parent::tearDown(); // TODO: Change the autogenerated stub
	}

	public function testUserCount()
	{
		$results = $this->users->findAll();

		$this->assertCount(4, $results);
	}
}